model: 'PlainRepConv'
comment: 'Test_kihwan_baseline_X2'
## parameters for plain
scale: 2
colors: 3
m_plainsr: 4
c_plainsr: 64
with_bn: 0
act_type: 'relu'
pretrain:

## loss function & optimizer
loss: 'l1'

## optimizer:
optimizer: adam
lr: 0.0005

## scheduler:
scheduler: 'CosineAnnealingWarmRestarts'
decays: [200, 400, 600]
gamma: 0.5
wd: 0.0
min_lr: 0.000001

## parameters for model training
epochs: 800

patch_size: 192
batch_size: 8
data_repeat: 20
data_augment: 1

log_every: 100
test_every: 1
log_path: "./experiments"
log_name:

wandb: True

## hardware specification
threads: 1

## data specification
data_path: '/dataset/SR/RLSR/DIV2K_X2/'
test_path: '/dataset/SR/RLSR/val_phase/'
eval_sets: ['DIV2K']
