model: 'RTSRN'
comment: 'CVPRW2023'
## parameters for plain
scale: 2

## loss function & optimizer
loss: 'l1'

## optimizer:
optimizer: adam
lr: 0.0002

## scheduler:
scheduler: 'MultistepLR'
decays: [200, 400, 600]
gamma: 0.5
wd: 0.0

## parameters for model training
epochs: 800

patch_size: 192
batch_size: 16
data_repeat: 20
data_augment: 1

log_every: 100
test_every: 1
log_path: "./experiments/RTSRN"
log_name:
save_val_image: False

wandb: True

## Fp16 training
mixed_pred: True
normalize: True

## hardware specification
threads: 1

## data specification
data_path: '/dataset/SR/RLSR/sota/DIV2K_X2/'
test_path: '/dataset/SR/RLSR/sota/val_phase_X2/'
eval_sets: ['DIV2K']
