model: 'plainsr2'
comment: 'Pre-Test-Step'
## parameters for plain
scale: 3
colors: 3
m_plainsr: 6
c_plainsr: 48
with_bn: 0
act_type: 'relu'
pretrain:

## loss function & optimizer
loss: 'l1'

## optimizer:
optimizer: adam
lr: 0.0005

## scheduler:
scheduler: 'MultiStepLR'
decays: [500]
gamma: 0.5
wd: 0.0

## parameters for model training
epochs: 500

patch_size: 96
batch_size: 32
data_repeat: 20
data_augment: 1

log_every: 100
test_every: 1
log_path: "./experiments"
log_name:

wandb: True

## hardware specification
gpu_ids: [0]
threads: 1

## data specification
data_path: '/dataset/SR/RLSR/DIV2K'
eval_sets: ['DIV2K']